import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

describe('Electron golden path lifecycle contract', () => {
  it('awaits child-process, CDP, and fixture-server cleanup before returning', async () => {
    const launcher = await readFile(new URL('../scripts/dev-stable.mjs', import.meta.url), 'utf8')
    const driver = await readFile(new URL('../scripts/cdp-driver.mjs', import.meta.url), 'utf8')
    const runner = await readFile(new URL('../scripts/golden-path-electron.mjs', import.meta.url), 'utf8')
    const protocol = await readFile(new URL('../scripts/golden-path-runner.mjs', import.meta.url), 'utf8')
    const rightPanel = await readFile(new URL('../src/renderer/src/components/RightPanel.tsx', import.meta.url), 'utf8')

    expect(launcher).toContain('const stop = async ()')
    expect(launcher).toContain('Promise.all([waitForProcessExit')
    expect(launcher).toContain("child.kill('SIGKILL')")
    expect(driver).toContain('const close = async ()')
    expect(driver).toContain('Promise.race')
    expect(runner).toContain('await driver?.close()')
    expect(runner).toContain('await launcher?.stop()')
    expect(runner).toContain('await closeServer(imageServer)')
    expect(runner).toContain('closeAllConnections')
    expect(protocol).toContain('clearTimeout(timeoutHandle)')
    expect(runner).toContain("id: 'selection-toolbar'")
    expect(runner).toContain('NOVEL_STUDIO_CDP_PORT')
    expect(runner).toContain('timeoutMs: 60_000')
    expect(runner).toContain("id: 'workflow-cancel-ui'")
    expect(runner).toContain("data-testid=\\\"workflow-run\\\"")
    expect(runner).toContain('getClientRects()')
    expect(runner).toContain(".novel-editor[contenteditable=\"true\"]")
    expect(runner).toContain("编辑器无法获得焦点")
    expect(driver).toContain('buttons: 1')
    expect(driver).toContain("type: 'mousePressed', x: from.x, y: from.y, button: 'left', buttons: 1")
    expect(driver).toContain("type: 'mouseReleased', x: to.x, y: to.y, button: 'left', buttons: 0")
    expect(rightPanel).toContain('data-running={running ?')
    expect(runner).toContain("button.dataset.running === 'true'")
    expect(runner).toContain('button[data-action="select"]')
    expect(runner).toContain("item.textContent?.includes('重试')")
    expect(runner).toContain("['failed', '失败'].includes(status)")
  })
})
